export const JSON_SCHEMA_DRAFT = 'https://json-schema.org/draft/2020-12/schema';

export const JSON_SCHEMA_UNHANDLED_KEYS = new Set([
  'if',
  'then',
  'else',
  'prefixItems',
  'patternProperties',
  'dependentRequired',
  'dependentSchemas',
  'contentEncoding',
  'contentMediaType',
  'contentSchema',
  'propertyNames',
  'minProperties',
  'maxProperties',
  'multipleOf',
  'uniqueItems',
  'readOnly',
  'writeOnly',
  'deprecated',
  'examples',
  'default',
  'unevaluatedItems',
  '$comment',
  '$schema',
  '$id',
  '$anchor',
  '$dynamicAnchor',
  '$dynamicRef',
]);
